export const HERO = "hero";
export const HERO_TITLE = "HERO";
export const DESCRIPTION = "description";
export const DESCRIPTION_TITLE = "DESCRIPTION";
export const NAVLINKS = "navLinks";
export const NAVLINKS_TITLE = "NAVIGATION LINKS";
export const SLIDER = "slider";
export const SLIDER_TITLE = "SLIDER";
export const TEAM = "team";
export const TEAM_TITLE = "TEAM";
export const PRODUCTS = "products";
export const PRODUCTS_TITLE = "PRODUCTS";
export const NAVCARD = "navCard";
export const NAVCARD_TITLE = "NAVIGATION CARD";
export const SERVICES = "services";
export const SERVICES_TITLE = "SERVICES";
export const CONTACT_DETAILS = "contactDetails";
export const CONTACT_DETAILS_TITLE = "CONTACT DETAILS";
export const CONTACT_FORM = "contactForm";
export const CONTACT_FORM_TITLE = "CONTACT FORM";
// REFERANCE DOCS
export const HEADER = "header";
export const HEADER_TITLE = "HEADER";
export const FOOTER = "footer";
export const FOOTER_TITLE = "FOOTER";
// PAGES
export const HOME_PAGE = "homePage";
export const HOME_PAGE_TITLE = "HOME PAGE";
export const PRODUCTS_PAGE = "productsPage";
export const PRODUCTS_PAGE_TITLE = "PRODUCTS PAGE";
export const SERVICES_PAGE = "servicesPage";
export const SERVICES_PAGE_TITLE = "SERVICES PAGE";
export const CONTACT_PAGE = "contactPage";
export const CONTACT_PAGE_TITLE = "CONTACT PAGE";
export const ABOUT_PAGE = "aboutPage";
export const ABOUT_PAGE_TITLE = "ABOUT PAGE";
// OTHER
export const STYLES = "styles";
export const STYLES_TITLE = "STYLES";
